### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheStaticVoid** [TheStaticVoid/StaTechCompanionMod#1]
- [ ] Tier 5-10 Ad Astra rockets
- [ ] Fix the Forge Hammer to be a block entity
- [ ] Try and fix the JAVD being full brightness
- [ ] Mega Torch should block Slime spawns
